name: Rowe Portrait Studios
favicon: null
layout_spectrum: 0.35507873352617025
typography_spectrum: 0.43097498710267246
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.19989768811501563
  lightness: 0.7126424910966307
  saturation: 0.966115765273571
  rhythmicContrast: 0.9309159810654819
purpose: []
