name: Rowe Portrait Studios
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.966115765273571
  lightness: 0.7126424910966307
  brandStrength: 0.367884
  brandColors:
    - '#FFFFFF'
    - '#8B8B8B'
    - '#010101'
    - '#D0D0D0'
    - '#656565'
  rhythmicContrast: 0.9309159810654819
typography_spectrum: 0.5934479
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
layout_spectrum: 1
